### ISSUE TITLE
Is there a way to reduce "Waiting for more resources." messages?

### ISSUE THREAD

**Issue by pakiessling** [snakemake/snakemake-executor-plugin-slurm#203]
I have hundreds of thousands of this line in my log files.

I am submitting lots of jobs against a total job limit.

Can I somehow reduce the amount of times this is printed?
It makes it difficult to understand my logs

*[*Software Versions]**

```
$ snakemake --version
8.25.5
$ mamba list | grep "snakemake-executor-plugin-slurm"
snakemake-executor-plugin-slurm 0.11.2                   pypi_0    pypi
snakemake-executor-plugin-slurm-jobstep 0.2.1       pypi_0    pypi
$ sinfo --version
slurm 22.05.4
```

My config.yaml

```
executor: slurm

default-resources:
    mem_mb: 8_000 # default rules memory in MB (you can keep this value)
    gpu: 0
    slurm_account: p0020567
    runtime: 60

set-resources:
    explorer:
        mem_mb: 256_000
        slurm_partition: c23mm # use a valid partition/queue name on your cluster (with enough RAM)
    image_write:
        mem_mb: 64_000
        slurm_partition: c23ms # use a valid partition/queue name on your cluster (with a large walltime)
    to_spatialdata:
        mem_mb: 128_000
    patch_segmentation_baysor:
        mem_mb: 128_000
        slurm_partition: c23ms # use a valid partition/queue name on your cluster (with at least 2h of walltime)
    patch_segmentation_comseg:
        mem_mb: 128_000
    aggregate:
        mem_mb: 64_000
    patchify_transcripts:
        mem_mb: 32_000
    report:
        mem_mb: 32_000
    resolve_cellpose:
        mem_mb: 32_000

# other options (you can keep the default values)
restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True

```

File that contains the offending line: `.snakemake/log/2025-01-23T154554.371429.snakemake.log`
How the pipeline is run: 
`nohup snakemake --workflow-profile slurm --config data_path=111-AF-heart-500 --configfile merfish.yml  > 111.log &`
