### ISSUE TITLE
`slurm_extra` is incorrectly interpolated

### ISSUE THREAD

**Issue by SilvanCodes** [snakemake/snakemake-executor-plugin-slurm#218]
**Software Versions**

I am inside a conda env as follows:
```yaml
name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=8.29.0
  - snakemake-executor-plugin-slurm=0.15.1
```
and `sinfo --version` reports `slurm 24.11.1`.

**Describe the bug**

Using `slurm_extra: "'-G 2'"` in a snakemake profile is interpolated including the single quotes.

**Logs**

**Minimal example**
I have a profile like so:
```yaml
executor: slurm

default-resources:
    ...

set-resources:
    <rule>:
        slurm_partition: "gpu"
        mem: "64gb"
        runtime: 60 # 1 hour
        slurm_extra: "'-G 2'"
```

resulting in a command as follows:

```
sbatch <omitted> -p gpu -t 60 --mem 64000 '-G 2' <omitted>
```

Notice the `slurm_extra` appears quoted in the constructed command, resulting in

```
WorkflowError:
SLURM sbatch failed. The error message was sbatch: error: Batch job submission failed: Requested node configuration is not available
```

**Additional context**
When the option is specified inside the `Snakefile` as

```
rule <rule>:
    ...
    resources:
        slurm_extra="-G 2"
```

it is parsed correctly.
