### ISSUE TITLE
Inconsistent handling of gres in profiles

### ISSUE THREAD

**Issue by w8jcik** [snakemake/snakemake-executor-plugin-slurm#248]
**Software Versions**

Snakemake 9.1.3
snakemake-executor-plugin-slurm 1.1.0

**Describe the bug**

This works

```yaml
default-resources:
  gres: "'gpu:1'"
```

but with `gres` set in a rule, in the same profile file

```yaml
set-resources:
  "some_rule":
    ...
    gres: "'gpu:1'"
```

following error appears

```
WorkflowError:
Invalid GRES format: 'gpu:1'. Expected format: '<name>:<number>' or '<name>:<type>:<number>' (e.g., 'gpu:1' or 'gpu:tesla:2')
```

Aside from failing submission, the message suggests to use format that is already used.
