### ISSUE TITLE
setting ntasks for non-MPI jobs

### ISSUE THREAD

**Issue by tatumdmortimer** [snakemake/snakemake-executor-plugin-slurm#40]
I am working on transitioning my snakemake workflows to Snakemake v8. However, when I use this plugin with a profile, I get the following error message:
`WorkflowError:
SLURM job submission failed. The error message was sbatch: error: You must specify a number of tasks.
sbatch: error: Batch job submission failed: Job size specification needs to be provided`

Here are the versions of Snakemake, this plugin, and slurm that I am working with:
```
Snakemake 8.5.2
snakemake-executor-plugin-slurm 0.3.2
slurm 23.02.4
```

Here is my profile:
```
executor: "slurm"
software-deployment-method: "conda"
latency-wait: 60
jobs: 100
default-resources:
  runtime: 10
  slurm_partition: "batch"
  mem_mb: 4000
  tasks: 1
  nodes: 1
```

I cloned the repository, removed the `if job.resources.get("mpi", False):` on line 107 of `__init__.py`, and reinstalled the plugin. This seems to have fixed the issue for me. Is there a reason these were only included in the sbatch command for mpi jobs?

Thanks!
